# RGB Channels
RED_CHANNEL = 0
GREEN_CHANNEL = 1
BLUE_CHANNEL = 2

# Crop Aspect Ratios
CROP_CUSTOM = 0
CROP_1_1 = 1
CROP_CIRCLE = 2

# Flip Directions
FLIP_VERTICAL = 0
FLIP_HORIZONTAL = 1
FLIP_VERTICAL_HORIZONTAL = 2
